erDiagram

  fixflo_activity {
    INTUNSIGNED id PK
    CHAR uuid
    VARCHAR log_name
    TEXT description
    VARCHAR company_id
    VARCHAR subject_id
    VARCHAR subject_type
    VARCHAR causer_id
    VARCHAR causer_type
    TEXT properties
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fixflo_board_groups {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR board_uuid FK
    CHAR group_uuid FK
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
    BIT can_edit
  }

  fixflo_board_members {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR board_uuid FK
    CHAR user_uuid FK
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
    BIT can_edit
  }

  fixflo_board_orders {
    CHAR board_uuid PK
    CHAR user_uuid PK
    INT order
  }

  fixflo_boards {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR company_uuid FK
    CHAR owner_uuid FK
    VARCHAR name
    BIT is_sample
    JSON tags
    JSON params
    VARCHAR type
    VARCHAR slug
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fixflo_boundaries {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR zone_uuid FK
    GEOMETRY boundary
    GEOMETRY location
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fixflo_cargo_grades {
    INTUNSIGNED id PK
    CHAR uuid UK
    CHAR company_uuid FK
    VARCHAR name
    VARCHAR display_name
    JSON aliases
    VARCHAR slug
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fixflo_cell_comments {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR company_uuid FK
    CHAR user_uuid FK
    CHAR subject_uuid
    VARCHAR subject
    VARCHAR content
    JSON cell
    VARCHAR slug
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fixflo_charterers {
    INTUNSIGNED id PK
    CHAR uuid UK
    VARCHAR name
    VARCHAR display_name
    JSON aliases
    VARCHAR slug
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fixflo_chat_messages {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR chat_session_uuid FK
    CHAR user_uuid FK
    TEXT content
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fixflo_chat_participants {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR chat_session_uuid FK
    CHAR user_uuid FK
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fixflo_chat_sessions {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR group_uuid FK
    VARCHAR type
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fixflo_color_codes {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR company_uuid FK
    VARCHAR name
    VARCHAR color
    VARCHAR slug
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fixflo_column_states {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR user_uuid FK
    CHAR source_uuid
    VARCHAR source
    JSON state
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fixflo_companies {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR owner_uuid FK
    VARCHAR name
    VARCHAR status
    VARCHAR slug
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fixflo_completed_tours {
    BIGINTUNSIGNED id PK
    CHAR user_uuid FK
    VARCHAR tour
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fixflo_confidentiality_levels {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR company_uuid FK
    VARCHAR name
    VARCHAR slug
    VARCHAR filter
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fixflo_files {
    INTUNSIGNED id PK
    CHAR uuid UK
    CHAR company_uuid FK
    CHAR uploader_uuid FK
    CHAR key_uuid
    VARCHAR caption
    VARCHAR key
    VARCHAR bucket
    VARCHAR folder
    VARCHAR etag
    TEXT data_params
    VARCHAR original_filename
    VARCHAR type
    VARCHAR content_type
    INT file_size
    VARCHAR slug
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fixflo_fixture_groups {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR company_uuid FK
    CHAR owner_uuid FK
    VARCHAR name
    VARCHAR status
    BIT shared_with_company
    VARCHAR slug
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fixflo_fixture_set_groups {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR set_uuid FK
    CHAR group_uuid FK
    VARCHAR status
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fixflo_fixture_sets {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR company_uuid FK
    CHAR owner_uuid FK
    VARCHAR name
    VARCHAR status
    VARCHAR slug
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fixflo_fixture_values {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR fixture_uuid FK
    CHAR relation_uuid
    VARCHAR key
    VARCHAR label
    TEXT pattern
    VARCHAR entry
    INT pos
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
    VARCHAR rate
    CHAR rate_binded_to
    BIT rate_bind_primary
  }

  fixflo_fixtures {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR set_uuid FK
    CHAR updated_by_uuid FK
    CHAR created_by_uuid FK
    CHAR vessel_uuid FK
    CHAR load_port_uuid FK
    CHAR discharge_port_uuid FK
    TEXT raw_text
    INT import_position
    VARCHAR charterer
    CHAR charterer_uuid FK
    VARCHAR laycan
    DATETIME laycan_range_start
    DATETIME laycan_range_end
    VARCHAR quantity
    VARCHAR grade
    CHAR grade_uuid FK
    VARCHAR rate
    VARCHAR status
    VARCHAR comments
    VARCHAR load
    VARCHAR discharge
    VARCHAR vessel
    VARCHAR cell_classname
    VARCHAR confidentiality
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
    BIT is_duplicate
    CHAR duplicate_source_uuid FK
    CHAR duplicate_fixture_uuid FK
    BIT internal
    BIT ignore_as_duplicate
    VARCHAR updated_by
    VARCHAR created_by
  }

  fixflo_free_board_columns {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR board_uuid FK
    VARCHAR label
    VARCHAR key
    BIT read_only
    INT order
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fixflo_free_board_inputs {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR board_uuid FK
    INT row
    INT column
    VARCHAR key
    TEXT value
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fixflo_generated_reports {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR user_uuid FK
    CHAR source_uuid
    CHAR report_template_uuid FK
    VARCHAR format
    VARCHAR sort
    JSON fixtures
    JSON filters
    BIT saved
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
    VARCHAR source_type
  }

  fixflo_group_members {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR user_uuid FK
    CHAR group_uuid FK
    VARCHAR status
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fixflo_groups {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR owner_uuid FK
    VARCHAR name
    VARCHAR status
    VARCHAR slug
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
    VARCHAR company_uuid FK
  }

  fixflo_login_attempts {
    INTUNSIGNED id PK
    VARCHAR uuid UK
    VARCHAR session_uuid FK
    VARCHAR identity
    VARCHAR password
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fixflo_manual_cache_updates {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR resource_uuid
    VARCHAR resource_class
    VARCHAR update_method
    VARCHAR cache_key_pattern
    BIT completed
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fixflo_migrations {
    INTUNSIGNED id PK
    VARCHAR migration
    INT batch
  }

  fixflo_notes {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR company_uuid FK
    CHAR for_uuid
    CHAR user_uuid FK
    TEXT content
    VARCHAR for
    VARCHAR scope
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fixflo_password_resets {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    VARCHAR email
    VARCHAR token
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fixflo_permissions {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    VARCHAR slug
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
    VARCHAR subject
  }

  fixflo_report_templates {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR company_uuid FK
    CHAR user_uuid FK
    VARCHAR name
    TEXT header
    JSON columns
    VARCHAR case
    VARCHAR format
    BIT zone_slash
    BIT shared_with_company
    VARCHAR slug
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fixflo_report_type_sorts {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR report_type_uuid FK
    VARCHAR sort_by
    INT order
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fixflo_report_type_sources {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR report_type_uuid FK
    CHAR board_uuid FK
    INT order
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fixflo_report_types {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR company_uuid FK
    CHAR user_uuid FK
    CHAR report_template_uuid FK
    VARCHAR name
    VARCHAR description
    VARCHAR format
    JSON filters
    VARCHAR slug
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fixflo_reports {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR user_uuid FK
    CHAR report_type_uuid FK
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fixflo_role_permissions {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR role_uuid FK
    CHAR permission_uuid FK
    BIT create
    BIT read
    BIT update
    BIT delete
    BIT export
    BIT import
    BIT share
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fixflo_roles {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR company_uuid FK
    VARCHAR name
    VARCHAR slug
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fixflo_saved_filters {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR user_uuid FK
    CHAR company_uuid FK
    CHAR for_uuid
    VARCHAR name
    VARCHAR for
    JSON params
    BIT shared_with_company
    VARCHAR slug
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fixflo_saved_reports {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR user_uuid FK
    CHAR company_uuid FK
    CHAR report_type_uuid FK
    VARCHAR name
    VARCHAR description
    VARCHAR format
    VARCHAR sort
    BIT shared_with_company
    VARCHAR slug
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
    JSON quantity
  }

  fixflo_sessions {
    INTUNSIGNED id PK
    VARCHAR uuid UK
    VARCHAR user_uuid FK
    VARCHAR company_uuid FK
    VARCHAR ip_address
    TEXT token_hash
    VARCHAR origin_app
    VARCHAR x_forwarded_for
    VARCHAR user_agent
    VARCHAR isp
    VARCHAR hostname
    VARCHAR timezone
    VARCHAR currency
    VARCHAR country
    VARCHAR region
    VARCHAR city
    VARCHAR postal_code
    VARCHAR longitude
    VARCHAR latitude
    JSON info
    JSON threat
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP expire_at
  }

  fixflo_sidebar_folder_items {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR sidebar_folder_uuid FK
    CHAR item_uuid
    VARCHAR item_type
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fixflo_sidebar_folders {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR user_uuid FK
    VARCHAR name
    VARCHAR icon
    VARCHAR slug
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
    VARCHAR type
  }

  fixflo_sub_cargo_grades {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR parent_uuid FK
    CHAR cargo_grade_uuid FK
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fixflo_user_confidentiality_settings {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR user_uuid FK
    CHAR level
    VARCHAR font_color
    BIT font_bold
    BIT font_italic
    VARCHAR background_color
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fixflo_users {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR company_uuid FK
    CHAR role_uuid FK
    VARCHAR name
    VARCHAR email UK
    VARCHAR phone_number
    VARCHAR timezone
    JSON layout_state
    TIMESTAMP email_verified_at
    TIMESTAMP last_login
    VARCHAR password
    VARCHAR status
    VARCHAR type
    VARCHAR slug
    VARCHAR remember_token
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fixflo_vessels {
    INTUNSIGNED id PK
    CHAR uuid UK
    CHAR created_by_uuid FK
    CHAR company_uuid FK
    VARCHAR name
    VARCHAR ex_name
    VARCHAR imo
    VARCHAR mmsi
    VARCHAR call_sign
    VARCHAR hull
    VARCHAR age
    VARCHAR flag
    VARCHAR type
    VARCHAR record_type
    VARCHAR division
    VARCHAR kind
    VARCHAR category
    VARCHAR class
    JSON company
    JSON measurement
    JSON mechanical
    JSON history
    BIT scrapped
    BIT total_loss
    BIT cancelled
    BIT active
    DATETIME delivery_date
    VARCHAR slug
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
    VARCHAR fleet
  }

  fixflo_widgets {
    INTUNSIGNED id PK
    CHAR uuid UK
    CHAR company_uuid FK
    CHAR owner_uuid FK
    VARCHAR name
    CHAR source_uuid
    VARCHAR source_type
    VARCHAR x_axis
    VARCHAR y_axis
    VARCHAR type
    BIT shared_with_company
    VARCHAR slug
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fixflo_zones {
    INTUNSIGNED id PK
    CHAR uuid UK
    CHAR company_uuid
    VARCHAR name
    VARCHAR display_name
    VARCHAR country
    GEOMETRY location
    JSON aliases
    VARCHAR type
    VARCHAR slug
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_activity {
    INTUNSIGNED id PK
    CHAR uuid
    VARCHAR log_name
    TEXT description
    CHAR company_id
    CHAR subject_id
    VARCHAR subject_type
    VARCHAR event
    CHAR causer_id
    VARCHAR causer_type
    TEXT properties
    CHAR batch_uuid
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_api_credentials {
    INTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    VARCHAR user_uuid FK
    VARCHAR company_uuid FK
    VARCHAR name
    VARCHAR key
    VARCHAR secret
    INT test_mode
    VARCHAR api
    JSON browser_origins
    DATETIME last_used_at
    DATETIME expires_at
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_api_events {
    INTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    VARCHAR public_id UK
    VARCHAR company_uuid
    VARCHAR api_credential_uuid
    VARCHAR event
    VARCHAR source
    JSON data
    VARCHAR description
    VARCHAR method
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_api_request_logs {
    INTUNSIGNED id PK
    VARCHAR _key
    CHAR uuid UK
    CHAR company_uuid FK
    CHAR api_credential_uuid FK
    VARCHAR public_id
    VARCHAR method
    VARCHAR path
    VARCHAR full_url
    VARCHAR status_code
    VARCHAR reason_phrase
    DECIMAL duration
    VARCHAR ip_address
    VARCHAR version
    VARCHAR source
    VARCHAR content_type
    JSON related
    JSON query_params
    JSON request_headers
    JSON request_body
    MEDIUMTEXT request_raw_body
    JSON response_headers
    JSON response_body
    MEDIUMTEXT response_raw_body
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fleetbase_billing_customers {
    BIGINTUNSIGNED id PK
    CHAR uuid
    CHAR company_uuid FK
    VARCHAR payment_gateway_id
    VARCHAR pm_type
    VARCHAR pm_last_four
    TIMESTAMP trial_ends_at
    JSON options
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_billing_payment_gateways {
    BIGINTUNSIGNED id PK
    CHAR uuid
    VARCHAR name
    VARCHAR code
    VARCHAR description
    VARCHAR api_key
    VARCHAR api_secret
    VARCHAR callback_url
    VARCHAR return_url
    VARCHAR webhook_secret
    CHAR logo_uuid FK
    CHAR backdrop_uuid FK
    JSON options
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_billing_plans {
    BIGINTUNSIGNED id PK
    CHAR uuid
    CHAR payment_gateway_uuid FK
    VARCHAR name
    TEXT description
    VARCHAR payment_gateway_id
    INT price
    BIT recurring
    VARCHAR billing_period
    VARCHAR interval
    INT trial_period_days
    JSON options
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_billing_subscription_items {
    BIGINTUNSIGNED id PK
    CHAR uuid
    CHAR subscription_uuid FK
    VARCHAR payment_gateway_id
    VARCHAR payment_gateway_product
    VARCHAR payment_gateway_price
    INT quantity
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_billing_subscriptions {
    BIGINTUNSIGNED id PK
    CHAR uuid
    CHAR company_uuid FK
    CHAR payment_gateway_uuid FK
    CHAR plan_uuid FK
    VARCHAR type
    VARCHAR payment_gateway_id
    VARCHAR payment_gateway_status
    VARCHAR payment_gateway_price
    INT quantity
    TIMESTAMP trial_ends_at
    TIMESTAMP ends_at
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_categories {
    INTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    VARCHAR public_id
    VARCHAR company_uuid
    VARCHAR parent_uuid
    VARCHAR owner_uuid
    VARCHAR owner_type
    VARCHAR name
    VARCHAR internal_id
    VARCHAR description
    JSON translations
    JSON tags
    JSON meta
    VARCHAR icon
    VARCHAR icon_color
    VARCHAR for
    BIT core_category
    VARCHAR slug
    VARCHAR order
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
    CHAR icon_file_uuid FK
  }

  fleetbase_chat_attachments {
    INTUNSIGNED id PK
    CHAR uuid
    VARCHAR public_id
    CHAR company_uuid FK
    CHAR sender_uuid FK
    CHAR chat_channel_uuid FK
    CHAR chat_message_uuid FK
    CHAR file_uuid FK
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fleetbase_chat_channels {
    INTUNSIGNED id PK
    CHAR uuid
    CHAR company_uuid FK
    CHAR created_by_uuid FK
    VARCHAR public_id
    VARCHAR name
    VARCHAR slug
    JSON meta
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fleetbase_chat_logs {
    BIGINTUNSIGNED id PK
    CHAR uuid
    VARCHAR public_id
    CHAR company_uuid FK
    CHAR chat_channel_uuid FK
    CHAR initiator_uuid FK
    VARCHAR event_type
    MEDIUMTEXT content
    JSON subjects
    JSON meta
    VARCHAR status
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fleetbase_chat_messages {
    INTUNSIGNED id PK
    CHAR uuid
    VARCHAR public_id
    CHAR company_uuid FK
    CHAR sender_uuid FK
    CHAR chat_channel_uuid FK
    MEDIUMTEXT content
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fleetbase_chat_participants {
    INTUNSIGNED id PK
    CHAR uuid
    VARCHAR public_id
    CHAR company_uuid FK
    CHAR user_uuid FK
    CHAR chat_channel_uuid FK
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fleetbase_chat_receipts {
    INTUNSIGNED id PK
    CHAR uuid
    VARCHAR public_id
    CHAR company_uuid FK
    CHAR participant_uuid FK
    CHAR chat_message_uuid FK
    TIMESTAMP read_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fleetbase_comments {
    INTUNSIGNED id PK
    CHAR uuid
    VARCHAR public_id UK
    CHAR company_uuid FK
    CHAR author_uuid FK
    CHAR parent_comment_uuid FK
    CHAR subject_uuid
    VARCHAR subject_type
    MEDIUMTEXT content
    JSON tags
    JSON meta
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fleetbase_companies {
    INTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    VARCHAR public_id UK
    VARCHAR stripe_id
    VARCHAR stripe_connect_id
    TIMESTAMP trial_ends_at
    VARCHAR card_last_four
    VARCHAR card_brand
    VARCHAR owner_uuid FK
    VARCHAR logo_uuid FK
    VARCHAR backdrop_uuid FK
    VARCHAR name
    VARCHAR website_url
    VARCHAR description
    JSON options
    VARCHAR phone
    VARCHAR currency
    VARCHAR country
    VARCHAR timezone
    VARCHAR place_uuid FK
    VARCHAR plan
    VARCHAR status
    VARCHAR type
    VARCHAR slug
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_company_users {
    INTUNSIGNED id PK
    VARCHAR _key
    CHAR uuid UK
    CHAR company_uuid FK
    CHAR user_uuid FK
    VARCHAR status
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_contacts {
    INTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    VARCHAR public_id UK
    VARCHAR internal_id
    CHAR company_uuid FK
    CHAR user_uuid
    CHAR photo_uuid FK
    VARCHAR name
    VARCHAR title
    VARCHAR email
    VARCHAR phone
    VARCHAR type
    VARCHAR slug
    JSON meta
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_custom_field_values {
    INTUNSIGNED id PK
    CHAR uuid
    CHAR company_uuid FK
    CHAR custom_field_uuid FK
    CHAR subject_uuid
    VARCHAR subject_type
    TEXT value
    VARCHAR value_type
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fleetbase_custom_fields {
    INTUNSIGNED id PK
    CHAR uuid
    CHAR company_uuid FK
    CHAR category_uuid
    CHAR subject_uuid
    VARCHAR subject_type
    VARCHAR name
    VARCHAR label
    VARCHAR type
    VARCHAR component
    JSON options
    BIT required
    BIT editable
    TEXT default_value
    JSON validation_rules
    JSON meta
    MEDIUMTEXT description
    MEDIUMTEXT help_text
    INT order
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fleetbase_dashboard_widgets {
    BIGINTUNSIGNED id PK
    CHAR uuid
    CHAR dashboard_uuid FK
    VARCHAR name
    VARCHAR component
    JSON grid_options
    JSON options
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fleetbase_dashboards {
    BIGINTUNSIGNED id PK
    CHAR uuid
    CHAR company_uuid
    CHAR user_uuid
    VARCHAR name
    BIT is_default
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_drivers {
    INTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    VARCHAR public_id UK
    VARCHAR internal_id
    CHAR company_uuid FK
    CHAR vehicle_uuid FK
    CHAR vendor_uuid FK
    VARCHAR vendor_type
    CHAR current_job_uuid FK
    CHAR user_uuid FK
    VARCHAR auth_token
    VARCHAR drivers_license_number
    VARCHAR signup_token_used
    MEDIUMTEXT avatar_url
    GEOMETRY location
    VARCHAR latitude
    VARCHAR longitude
    VARCHAR heading
    VARCHAR bearing
    VARCHAR speed
    VARCHAR altitude
    VARCHAR country
    VARCHAR city
    VARCHAR currency
    INT online
    VARCHAR status
    VARCHAR slug
    JSON meta
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_entities {
    INTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    VARCHAR public_id UK
    CHAR payload_uuid FK
    CHAR company_uuid FK
    CHAR driver_assigned_uuid FK
    CHAR supplier_uuid FK
    CHAR destination_uuid FK
    VARCHAR customer_uuid
    VARCHAR customer_type
    CHAR tracking_number_uuid FK
    MEDIUMTEXT photo_uuid
    CHAR category_uuid FK
    VARCHAR _import_id
    VARCHAR internal_id
    VARCHAR name
    VARCHAR type
    MEDIUMTEXT description
    VARCHAR currency
    MEDIUMTEXT barcode
    MEDIUMTEXT qr_code
    VARCHAR weight
    VARCHAR weight_unit
    VARCHAR length
    VARCHAR width
    VARCHAR height
    VARCHAR dimensions_unit
    INT declared_value
    VARCHAR sku
    VARCHAR price
    VARCHAR sale_price
    JSON meta
    VARCHAR slug
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_extension_installs {
    BIGINTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    CHAR extension_uuid FK
    VARCHAR company_uuid FK
    JSON config
    JSON meta
    JSON overwrite
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_extensions {
    INTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    VARCHAR public_id UK
    VARCHAR extension_id UK
    VARCHAR author_uuid FK
    VARCHAR category_uuid FK
    VARCHAR type_uuid FK
    VARCHAR name
    VARCHAR display_name
    VARCHAR key
    MEDIUMTEXT description
    JSON tags
    VARCHAR namespace
    VARCHAR version
    VARCHAR component_url
    VARCHAR website_url
    VARCHAR privacy_policy_url
    VARCHAR tos_url
    VARCHAR contact_email
    VARCHAR icon_uuid FK
    JSON domains
    BIT core_service
    VARCHAR internal_route
    VARCHAR fa_icon
    JSON meta
    VARCHAR meta_type
    JSON config
    VARCHAR secret
    VARCHAR client_token
    VARCHAR status
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
    VARCHAR slug
  }

  fleetbase_failed_jobs {
    BIGINTUNSIGNED id PK
    VARCHAR uuid UK
    TEXT connection
    TEXT queue
    LONGTEXT payload
    LONGTEXT exception
    TIMESTAMP failed_at
  }

  fleetbase_files {
    INTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    VARCHAR public_id
    VARCHAR company_uuid
    VARCHAR uploader_uuid
    VARCHAR subject_uuid
    VARCHAR disk
    VARCHAR caption
    LONGTEXT path
    VARCHAR subject_type
    VARCHAR bucket
    VARCHAR folder
    VARCHAR etag
    JSON meta
    MEDIUMTEXT data_params
    VARCHAR original_filename
    VARCHAR type
    VARCHAR content_type
    INT file_size
    VARCHAR slug
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_fleet_drivers {
    INTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    CHAR fleet_uuid FK
    CHAR driver_uuid FK
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_fleet_vehicles {
    INTUNSIGNED id PK
    VARCHAR _key
    CHAR uuid UK
    CHAR fleet_uuid FK
    CHAR vehicle_uuid FK
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_fleets {
    INTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    VARCHAR public_id UK
    CHAR company_uuid FK
    CHAR service_area_uuid FK
    CHAR zone_uuid FK
    CHAR vendor_uuid FK
    CHAR parent_fleet_uuid FK
    VARCHAR image_uuid
    VARCHAR name
    VARCHAR color
    VARCHAR task
    VARCHAR status
    VARCHAR slug
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_fuel_reports {
    INTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    VARCHAR public_id UK
    CHAR company_uuid FK
    CHAR driver_uuid FK
    CHAR vehicle_uuid FK
    CHAR reported_by_uuid FK
    MEDIUMTEXT report
    VARCHAR odometer
    GEOMETRY location
    VARCHAR amount
    VARCHAR currency
    VARCHAR volume
    VARCHAR metric_unit
    JSON meta
    VARCHAR status
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_group_users {
    INTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    CHAR group_uuid FK
    CHAR user_uuid FK
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_groups {
    INTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    VARCHAR company_uuid FK
    VARCHAR public_id
    VARCHAR name
    VARCHAR description
    VARCHAR slug
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_integrated_vendors {
    BIGINTUNSIGNED id PK
    VARCHAR _key
    CHAR uuid UK
    CHAR company_uuid FK
    CHAR created_by_uuid FK
    VARCHAR public_id
    VARCHAR host
    VARCHAR namespace
    VARCHAR webhook_url
    VARCHAR provider
    JSON credentials
    JSON options
    BIT sandbox
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_invites {
    BIGINTUNSIGNED id PK
    VARCHAR _key
    CHAR uuid UK
    CHAR company_uuid FK
    CHAR created_by_uuid FK
    CHAR subject_uuid
    VARCHAR subject_type
    VARCHAR public_id
    VARCHAR uri
    VARCHAR code
    VARCHAR protocol
    JSON recipients
    VARCHAR reason
    DATETIME expires_at
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_issues {
    INTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    VARCHAR public_id UK
    VARCHAR issue_id UK
    CHAR company_uuid FK
    CHAR driver_uuid FK
    CHAR vehicle_uuid FK
    CHAR assigned_to_uuid FK
    CHAR reported_by_uuid FK
    GEOMETRY location
    VARCHAR type
    VARCHAR category
    MEDIUMTEXT report
    VARCHAR priority
    JSON meta
    JSON tags
    DATETIME resolved_at
    VARCHAR status
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_login_attempts {
    INTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    VARCHAR identity
    VARCHAR password
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_migrations {
    INTUNSIGNED id PK
    VARCHAR migration
    INT batch
  }

  fleetbase_model_has_permissions {
    CHAR permission_id PK
    VARCHAR model_type PK
    CHAR model_uuid PK
  }

  fleetbase_model_has_policies {
    CHAR policy_id PK
    VARCHAR model_type PK
    CHAR model_uuid PK
  }

  fleetbase_model_has_roles {
    CHAR role_id PK
    VARCHAR model_type PK
    CHAR model_uuid PK
  }

  fleetbase_monitored_scheduled_task_log_items {
    BIGINTUNSIGNED id PK
    BIGINTUNSIGNED monitored_scheduled_task_id FK
    VARCHAR type
    JSON meta
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_monitored_scheduled_tasks {
    BIGINTUNSIGNED id PK
    VARCHAR name
    VARCHAR type
    VARCHAR cron_expression
    VARCHAR timezone
    VARCHAR ping_url
    DATETIME last_started_at
    DATETIME last_finished_at
    DATETIME last_failed_at
    DATETIME last_skipped_at
    DATETIME registered_on_oh_dear_at
    DATETIME last_pinged_at
    INT grace_time_in_minutes
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_notifications {
    CHAR id PK
    VARCHAR type
    VARCHAR notifiable_type
    CHAR notifiable_id
    TEXT data
    TIMESTAMP read_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_order_configs {
    INTUNSIGNED id PK
    CHAR uuid
    VARCHAR public_id
    CHAR company_uuid FK
    CHAR author_uuid FK
    CHAR category_uuid FK
    CHAR icon_uuid FK
    VARCHAR name
    VARCHAR namespace
    MEDIUMTEXT description
    VARCHAR key
    VARCHAR status
    VARCHAR version
    BIT core_service
    JSON flow
    JSON entities
    JSON tags
    JSON meta
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fleetbase_orders {
    INTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    VARCHAR public_id UK
    CHAR company_uuid FK
    CHAR created_by_uuid FK
    CHAR updated_by_uuid FK
    CHAR order_config_uuid FK
    VARCHAR internal_id
    CHAR customer_uuid
    VARCHAR customer_type
    VARCHAR facilitator_uuid
    VARCHAR facilitator_type
    CHAR session_uuid
    CHAR payload_uuid FK
    CHAR route_uuid FK
    CHAR transaction_uuid FK
    CHAR purchase_rate_uuid FK
    CHAR tracking_number_uuid FK
    CHAR driver_assigned_uuid FK
    JSON meta
    JSON options
    BIT dispatched
    DATETIME dispatched_at
    BIT adhoc
    INT adhoc_distance
    BIT started
    DATETIME started_at
    INT distance
    INT time
    BIT pod_required
    BIT is_route_optimized
    VARCHAR pod_method
    MEDIUMTEXT notes
    DATETIME scheduled_at
    VARCHAR type
    VARCHAR status
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_payloads {
    INTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    VARCHAR public_id UK
    CHAR company_uuid FK
    CHAR pickup_uuid FK
    CHAR dropoff_uuid FK
    CHAR return_uuid FK
    CHAR current_waypoint_uuid FK
    VARCHAR provider
    VARCHAR payment_method
    INT cod_amount
    VARCHAR cod_currency
    VARCHAR cod_payment_method
    VARCHAR type
    JSON meta
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_permissions {
    CHAR id
    VARCHAR name UK
    VARCHAR guard_name UK
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_personal_access_tokens {
    BIGINTUNSIGNED id PK
    VARCHAR tokenable_type
    CHAR tokenable_id "(DC2Type:guid)"
    VARCHAR name
    VARCHAR token UK
    TEXT abilities
    TIMESTAMP last_used_at
    TIMESTAMP expires_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_places {
    INTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    VARCHAR public_id UK
    VARCHAR _import_id
    CHAR company_uuid FK
    CHAR owner_uuid
    VARCHAR owner_type
    VARCHAR name
    VARCHAR street1
    VARCHAR street2
    VARCHAR city
    VARCHAR province
    VARCHAR postal_code
    VARCHAR neighborhood
    VARCHAR district
    VARCHAR building
    VARCHAR security_access_code
    VARCHAR country
    GEOMETRY location
    VARCHAR latitude
    VARCHAR longitude
    JSON meta
    VARCHAR phone
    MEDIUMTEXT remarks
    MEDIUMTEXT avatar_url
    VARCHAR type
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_policies {
    CHAR id PK
    VARCHAR _key
    CHAR company_uuid FK
    VARCHAR name
    VARCHAR guard_name
    VARCHAR description
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fleetbase_positions {
    BIGINTUNSIGNED id PK
    VARCHAR _key
    CHAR uuid UK
    CHAR company_uuid FK
    CHAR order_uuid FK
    CHAR destination_uuid FK
    CHAR subject_uuid
    VARCHAR subject_type
    GEOMETRY coordinates
    VARCHAR heading
    VARCHAR bearing
    VARCHAR speed
    VARCHAR altitude
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fleetbase_proofs {
    INTUNSIGNED id PK
    VARCHAR _key
    CHAR uuid UK
    VARCHAR public_id UK
    CHAR order_uuid
    CHAR subject_uuid
    VARCHAR subject_type
    CHAR company_uuid FK
    CHAR file_uuid FK
    LONGTEXT remarks
    LONGTEXT raw_data
    JSON data
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_purchase_rates {
    INTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    VARCHAR public_id UK
    JSON meta
    VARCHAR customer_uuid
    VARCHAR customer_type
    CHAR company_uuid FK
    CHAR transaction_uuid FK
    CHAR service_quote_uuid FK
    CHAR payload_uuid FK
    VARCHAR status
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_role_has_permissions {
    CHAR permission_id PK
    CHAR role_id PK
  }

  fleetbase_roles {
    CHAR id
    CHAR company_uuid FK
    VARCHAR name UK
    VARCHAR guard_name UK
    VARCHAR description
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fleetbase_routes {
    BIGINTUNSIGNED id PK
    VARCHAR _key
    CHAR uuid UK
    CHAR company_uuid FK
    CHAR order_uuid FK
    JSON details
    DOUBLE total_distance
    DOUBLE total_time
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_service_areas {
    INTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    VARCHAR public_id UK
    CHAR company_uuid FK
    VARCHAR name
    VARCHAR type
    VARCHAR country
    GEOMETRY border
    VARCHAR color
    VARCHAR stroke_color
    CHAR parent_uuid FK
    VARCHAR status
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_service_quote_items {
    INTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    CHAR service_quote_uuid FK
    VARCHAR amount
    VARCHAR currency
    VARCHAR details
    VARCHAR code
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_service_quotes {
    INTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    VARCHAR public_id UK
    VARCHAR request_id
    CHAR company_uuid FK
    CHAR payload_uuid FK
    CHAR service_rate_uuid FK
    INT amount
    VARCHAR currency
    JSON meta
    VARCHAR expired_at
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
    CHAR integrated_vendor_uuid FK
  }

  fleetbase_service_rate_fees {
    INTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    CHAR service_rate_uuid FK
    INT distance
    INT min
    INT max
    VARCHAR unit
    VARCHAR distance_unit
    INT fee
    VARCHAR currency
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_service_rate_parcel_fees {
    INTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    CHAR service_rate_uuid FK
    VARCHAR size
    VARCHAR length
    VARCHAR width
    VARCHAR height
    VARCHAR dimensions_unit
    VARCHAR weight
    VARCHAR weight_unit
    INT fee
    VARCHAR currency
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_service_rates {
    INTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    VARCHAR public_id UK
    CHAR company_uuid FK
    CHAR service_area_uuid FK
    CHAR zone_uuid FK
    CHAR order_config_uuid FK
    VARCHAR service_name
    VARCHAR service_type
    INT base_fee
    INT per_meter_flat_rate_fee
    VARCHAR per_meter_unit
    VARCHAR algorithm
    VARCHAR rate_calculation_method
    INT has_cod_fee
    VARCHAR cod_calculation_method
    INT cod_flat_fee
    INT cod_percent
    INT has_peak_hours_fee
    VARCHAR peak_hours_calculation_method
    INT peak_hours_flat_fee
    INT peak_hours_percent
    VARCHAR peak_hours_start
    VARCHAR peak_hours_end
    VARCHAR currency
    VARCHAR duration_terms
    INT estimated_days
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_settings {
    INTUNSIGNED id PK
    VARCHAR key UK
    JSON value
  }

  fleetbase_tracking_numbers {
    INTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    VARCHAR public_id UK
    CHAR company_uuid FK
    CHAR owner_uuid
    VARCHAR owner_type
    CHAR status_uuid FK
    VARCHAR tracking_number
    VARCHAR region
    MEDIUMTEXT qr_code
    MEDIUMTEXT barcode
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_tracking_statuses {
    INTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    VARCHAR public_id UK
    CHAR company_uuid FK
    CHAR tracking_number_uuid FK
    CHAR proof_uuid
    JSON meta
    VARCHAR status
    MEDIUMTEXT details
    VARCHAR code
    VARCHAR city
    VARCHAR province
    VARCHAR postal_code
    VARCHAR country
    GEOMETRY location
    VARCHAR latitude
    VARCHAR longitude
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_transaction_items {
    INTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    VARCHAR transaction_uuid FK
    VARCHAR amount
    VARCHAR currency
    VARCHAR details
    VARCHAR code
    JSON meta
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_transactions {
    INTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    VARCHAR public_id UK
    CHAR owner_uuid
    VARCHAR owner_type
    VARCHAR customer_uuid
    VARCHAR customer_type
    VARCHAR company_uuid FK
    CHAR gateway_uuid
    VARCHAR gateway_transaction_id
    VARCHAR gateway
    INT amount
    VARCHAR currency
    VARCHAR description
    VARCHAR type
    VARCHAR status
    JSON meta
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_types {
    INTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    VARCHAR company_uuid FK
    CHAR subject_uuid
    VARCHAR subject_type
    VARCHAR name
    VARCHAR description
    VARCHAR key
    VARCHAR slug
    VARCHAR for
    JSON meta
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_user_devices {
    INTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    VARCHAR public_id
    VARCHAR user_uuid FK
    VARCHAR platform
    MEDIUMTEXT token
    VARCHAR status
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_users {
    INTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    VARCHAR public_id UK
    VARCHAR company_uuid FK
    VARCHAR avatar_uuid FK
    VARCHAR username UK
    VARCHAR email
    VARCHAR phone
    VARCHAR password
    VARCHAR name
    VARCHAR date_of_birth
    VARCHAR timezone
    VARCHAR country
    VARCHAR ip_address
    VARCHAR last_login
    VARCHAR slug
    VARCHAR type
    VARCHAR status
    JSON meta
    VARCHAR remember_token
    DATETIME email_verified_at
    DATETIME phone_verified_at
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_vehicle_device_events {
    INTUNSIGNED id PK
    CHAR uuid
    CHAR vehicle_device_uuid FK
    JSON payload
    JSON meta
    VARCHAR ident
    VARCHAR protocol
    VARCHAR provider
    GEOMETRY location
    VARCHAR mileage
    VARCHAR state
    VARCHAR code
    VARCHAR reason
    MEDIUMTEXT comment
    TIMESTAMP resolved_at
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_vehicle_devices {
    INTUNSIGNED id PK
    CHAR uuid
    CHAR vehicle_uuid FK
    VARCHAR device_id
    VARCHAR device_provider
    VARCHAR device_type
    VARCHAR device_name
    VARCHAR device_location
    VARCHAR device_model
    VARCHAR manufacturer
    VARCHAR serial_number
    DATE installation_date
    DATE last_maintenance_date
    JSON meta
    JSON data
    BIT online
    VARCHAR status
    VARCHAR data_frequency
    TEXT notes
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_vehicles {
    INTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    VARCHAR public_id UK
    CHAR company_uuid FK
    CHAR vendor_uuid FK
    CHAR photo_uuid FK
    MEDIUMTEXT avatar_url
    GEOMETRY location
    VARCHAR speed
    VARCHAR heading
    VARCHAR altitude
    VARCHAR make
    VARCHAR model
    VARCHAR year
    VARCHAR trim
    VARCHAR type
    VARCHAR plate_number
    VARCHAR vin
    MEDIUMTEXT vin_data
    JSON meta
    JSON telematics
    JSON model_data
    VARCHAR status
    BIT online
    VARCHAR slug
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_vendors {
    INTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    VARCHAR public_id UK
    CHAR company_uuid FK
    CHAR place_uuid FK
    CHAR type_uuid FK
    CHAR connect_company_uuid FK
    CHAR logo_uuid FK
    VARCHAR name
    VARCHAR internal_id
    VARCHAR business_id
    INT connected
    VARCHAR email
    VARCHAR phone
    VARCHAR website_url
    VARCHAR country
    JSON meta
    JSON callbacks
    VARCHAR type
    VARCHAR status
    VARCHAR slug
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_verification_codes {
    INTUNSIGNED id PK
    VARCHAR _key
    CHAR uuid UK
    CHAR subject_uuid
    VARCHAR subject_type
    VARCHAR code
    VARCHAR for
    JSON meta
    DATETIME expires_at
    VARCHAR status
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_waypoints {
    INTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    VARCHAR public_id
    CHAR company_uuid FK
    CHAR place_uuid FK
    CHAR payload_uuid FK
    CHAR tracking_number_uuid FK
    VARCHAR _import_id
    VARCHAR type
    INT order
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_webhook_endpoints {
    INTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    VARCHAR company_uuid FK
    CHAR updated_by_uuid FK
    CHAR created_by_uuid FK
    VARCHAR api_credential_uuid FK
    VARCHAR url
    VARCHAR mode
    VARCHAR version
    VARCHAR description
    JSON events
    VARCHAR status
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_webhook_request_logs {
    INTUNSIGNED id PK
    VARCHAR _key
    CHAR uuid UK
    VARCHAR public_id UK
    CHAR company_uuid FK
    CHAR webhook_uuid FK
    CHAR api_credential_uuid FK
    CHAR api_event_uuid FK
    VARCHAR method
    VARCHAR status_code
    VARCHAR reason_phrase
    DECIMAL duration
    VARCHAR url
    INT attempt
    JSON meta
    JSON headers
    JSON response
    VARCHAR status
    DATETIME sent_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  fleetbase_zones {
    INTUNSIGNED id PK
    VARCHAR _key
    VARCHAR uuid UK
    VARCHAR public_id UK
    CHAR company_uuid FK
    CHAR service_area_uuid FK
    VARCHAR name
    MEDIUMTEXT description
    GEOMETRY border
    VARCHAR color
    VARCHAR stroke_color
    VARCHAR status
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_storefront_carts {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    VARCHAR public_id
    CHAR company_uuid FK
    CHAR user_uuid FK
    CHAR checkout_uuid FK
    VARCHAR customer_id
    VARCHAR unique_identifier
    VARCHAR currency
    VARCHAR discount_code
    JSON items
    JSON events
    DATETIME expires_at
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_storefront_checkouts {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    VARCHAR public_id
    CHAR company_uuid FK
    CHAR order_uuid FK
    CHAR cart_uuid FK
    CHAR store_uuid FK
    CHAR network_uuid FK
    CHAR gateway_uuid FK
    CHAR service_quote_uuid FK
    CHAR owner_uuid
    VARCHAR owner_type
    VARCHAR token
    INT amount
    VARCHAR currency
    BIT is_cod
    BIT is_pickup
    JSON options
    JSON cart_state
    BIT captured
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_storefront_gateways {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    VARCHAR public_id
    CHAR company_uuid FK
    CHAR created_by_uuid FK
    CHAR logo_file_uuid FK
    CHAR owner_uuid
    VARCHAR owner_type
    VARCHAR name
    VARCHAR description
    VARCHAR code
    VARCHAR type
    BIT sandbox
    JSON meta
    JSON config
    VARCHAR return_url
    VARCHAR callback_url
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_storefront_network_stores {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    VARCHAR network_uuid FK
    VARCHAR store_uuid FK
    CHAR category_uuid FK
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_storefront_networks {
    BIGINTUNSIGNED id PK
    VARCHAR public_id
    CHAR uuid UK
    VARCHAR created_by_uuid FK
    VARCHAR company_uuid FK
    CHAR logo_uuid FK
    CHAR backdrop_uuid FK
    VARCHAR name
    LONGTEXT key
    BIT online
    VARCHAR currency
    VARCHAR timezone
    VARCHAR pod_method
    JSON options
    JSON alertable
    VARCHAR description
    VARCHAR phone
    VARCHAR email
    VARCHAR website
    VARCHAR facebook
    VARCHAR instagram
    VARCHAR twitter
    JSON tags
    JSON translations
    VARCHAR slug
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_storefront_notification_channels {
    BIGINTUNSIGNED id PK
    CHAR uuid
    CHAR company_uuid FK
    CHAR created_by_uuid FK
    VARCHAR owner_uuid
    VARCHAR owner_type
    CHAR certificate_uuid FK
    JSON config
    JSON options
    VARCHAR name
    VARCHAR scheme
    VARCHAR app_key
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_storefront_payment_methods {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    VARCHAR public_id
    CHAR company_uuid FK
    CHAR store_uuid FK
    CHAR gateway_uuid FK
    CHAR owner_uuid
    VARCHAR owner_type
    VARCHAR gateway_id
    VARCHAR type
    VARCHAR brand
    VARCHAR last4
    JSON meta
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_storefront_product_addon_categories {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    VARCHAR product_uuid FK
    VARCHAR category_uuid FK
    JSON excluded_addons
    MEDIUMINT max_selectable
    BIT is_required
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_storefront_product_addons {
    BIGINTUNSIGNED id PK
    VARCHAR public_id
    CHAR uuid UK
    VARCHAR created_by_uuid FK
    VARCHAR category_uuid FK
    VARCHAR name
    VARCHAR description
    JSON translations
    INT price
    INT sale_price
    BIT is_on_sale
    VARCHAR slug
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_storefront_product_hours {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    VARCHAR product_uuid FK
    VARCHAR day_of_week
    TIME start
    TIME end
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_storefront_product_store_locations {
    BIGINTUNSIGNED id PK
    VARCHAR product_uuid FK
    VARCHAR store_location_uuid FK
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_storefront_product_variant_options {
    BIGINTUNSIGNED id PK
    VARCHAR public_id
    CHAR uuid UK
    VARCHAR product_variant_uuid FK
    VARCHAR name
    VARCHAR description
    JSON translations
    JSON meta
    INT additional_cost
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_storefront_product_variants {
    BIGINTUNSIGNED id PK
    VARCHAR public_id
    CHAR uuid UK
    VARCHAR product_uuid FK
    VARCHAR name
    VARCHAR description
    JSON translations
    JSON meta
    BIT is_multiselect
    BIT is_required
    MEDIUMINT min
    MEDIUMINT max
    VARCHAR slug
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_storefront_products {
    BIGINTUNSIGNED id PK
    VARCHAR public_id
    CHAR uuid UK
    VARCHAR company_uuid FK
    VARCHAR created_by_uuid FK
    VARCHAR primary_image_uuid FK
    VARCHAR store_uuid FK
    VARCHAR category_uuid FK
    VARCHAR name
    LONGTEXT description
    JSON tags
    JSON meta
    JSON translations
    MEDIUMTEXT qr_code
    MEDIUMTEXT barcode
    JSON youtube_urls
    VARCHAR sku
    INT price
    INT sale_price
    BIT is_on_sale
    BIT is_service
    BIT is_bookable
    BIT is_available
    BIT is_recommended
    BIT can_pickup
    VARCHAR currency
    VARCHAR status
    VARCHAR slug
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_storefront_reviews {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    VARCHAR public_id UK
    VARCHAR created_by_uuid FK
    CHAR customer_uuid FK
    CHAR subject_uuid
    VARCHAR subject_type
    MEDIUMINT rating
    TEXT content
    BIT rejected
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_storefront_store_hours {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    CHAR store_location_uuid FK
    VARCHAR day_of_week
    TIME start
    TIME end
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_storefront_store_locations {
    BIGINTUNSIGNED id PK
    VARCHAR public_id
    CHAR uuid UK
    VARCHAR store_uuid FK
    VARCHAR created_by_uuid FK
    VARCHAR place_uuid FK
    VARCHAR name
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_storefront_stores {
    BIGINTUNSIGNED id PK
    VARCHAR public_id
    CHAR uuid UK
    VARCHAR created_by_uuid FK
    VARCHAR company_uuid FK
    VARCHAR logo_uuid FK
    CHAR backdrop_uuid FK
    VARCHAR name
    LONGTEXT description
    VARCHAR phone
    VARCHAR email
    VARCHAR website
    VARCHAR facebook
    VARCHAR instagram
    VARCHAR twitter
    JSON tags
    JSON translations
    LONGTEXT key
    BIT online
    VARCHAR currency
    VARCHAR timezone
    VARCHAR pod_method
    JSON options
    JSON alertable
    JSON meta
    VARCHAR slug
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fleetbase_storefront_votes {
    BIGINTUNSIGNED id PK
    CHAR uuid UK
    VARCHAR public_id UK
    VARCHAR created_by_uuid FK
    CHAR customer_uuid FK
    CHAR subject_uuid
    VARCHAR subject_type
    VARCHAR type
    TIMESTAMP deleted_at
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  fixflo_boards ||--o{ fixflo_board_groups : "foreign key"
  fixflo_boards ||--o{ fixflo_board_members : "foreign key"
  fixflo_boards ||--o{ fixflo_free_board_columns : "foreign key"
  fixflo_boards ||--o{ fixflo_free_board_inputs : "foreign key"
  fixflo_boards ||--o{ fixflo_report_type_sources : "foreign key"
  fixflo_cargo_grades ||--o{ fixflo_fixtures : "foreign key"
  fixflo_cargo_grades ||--o{ fixflo_sub_cargo_grades : "foreign key"
  fixflo_charterers ||--o{ fixflo_fixtures : "foreign key"
  fixflo_chat_sessions ||--o{ fixflo_chat_messages : "foreign key"
  fixflo_chat_sessions ||--o{ fixflo_chat_participants : "foreign key"
  fixflo_companies ||--o{ fixflo_boards : "foreign key"
  fixflo_companies ||--o{ fixflo_cargo_grades : "foreign key"
  fixflo_companies ||--o{ fixflo_cell_comments : "foreign key"
  fixflo_companies ||--o{ fixflo_color_codes : "foreign key"
  fixflo_companies ||--o{ fixflo_confidentiality_levels : "foreign key"
  fixflo_companies ||--o{ fixflo_files : "foreign key"
  fixflo_companies ||--o{ fixflo_fixture_groups : "foreign key"
  fixflo_companies ||--o{ fixflo_fixture_sets : "foreign key"
  fixflo_companies ||--o{ fixflo_groups : "foreign key"
  fixflo_companies ||--o{ fixflo_notes : "foreign key"
  fixflo_companies ||--o{ fixflo_report_templates : "foreign key"
  fixflo_companies ||--o{ fixflo_report_types : "foreign key"
  fixflo_companies ||--o{ fixflo_roles : "foreign key"
  fixflo_companies ||--o{ fixflo_saved_filters : "foreign key"
  fixflo_companies ||--o{ fixflo_saved_reports : "foreign key"
  fixflo_companies ||--o{ fixflo_sessions : "foreign key"
  fixflo_companies ||--o{ fixflo_users : "foreign key"
  fixflo_companies ||--o{ fixflo_vessels : "foreign key"
  fixflo_companies ||--o{ fixflo_widgets : "foreign key"
  fixflo_fixture_sets ||--o{ fixflo_fixture_set_groups : "foreign key"
  fixflo_fixture_sets ||--o{ fixflo_fixtures : "foreign key"
  fixflo_fixtures ||--o{ fixflo_fixture_values : "foreign key"
  fixflo_fixtures ||--o{ fixflo_fixtures : "foreign key"
  fixflo_groups ||--o{ fixflo_board_groups : "foreign key"
  fixflo_groups ||--o{ fixflo_chat_sessions : "foreign key"
  fixflo_groups ||--o{ fixflo_fixture_set_groups : "foreign key"
  fixflo_groups ||--o{ fixflo_group_members : "foreign key"
  fixflo_permissions ||--o{ fixflo_role_permissions : "foreign key"
  fixflo_report_templates ||--o{ fixflo_generated_reports : "foreign key"
  fixflo_report_templates ||--o{ fixflo_report_types : "foreign key"
  fixflo_report_types ||--o{ fixflo_report_type_sorts : "foreign key"
  fixflo_report_types ||--o{ fixflo_report_type_sources : "foreign key"
  fixflo_report_types ||--o{ fixflo_reports : "foreign key"
  fixflo_report_types ||--o{ fixflo_saved_reports : "foreign key"
  fixflo_roles ||--o{ fixflo_role_permissions : "foreign key"
  fixflo_roles ||--o{ fixflo_users : "foreign key"
  fixflo_sessions ||--o{ fixflo_login_attempts : "foreign key"
  fixflo_sidebar_folders ||--o{ fixflo_sidebar_folder_items : "foreign key"
  fixflo_sub_cargo_grades ||--o{ fixflo_sub_cargo_grades : "foreign key"
  fixflo_users ||--o{ fixflo_board_members : "foreign key"
  fixflo_users ||--o{ fixflo_boards : "foreign key"
  fixflo_users ||--o{ fixflo_cell_comments : "foreign key"
  fixflo_users ||--o{ fixflo_chat_messages : "foreign key"
  fixflo_users ||--o{ fixflo_chat_participants : "foreign key"
  fixflo_users ||--o{ fixflo_column_states : "foreign key"
  fixflo_users ||--o{ fixflo_companies : "foreign key"
  fixflo_users ||--o{ fixflo_completed_tours : "foreign key"
  fixflo_users ||--o{ fixflo_files : "foreign key"
  fixflo_users ||--o{ fixflo_fixture_groups : "foreign key"
  fixflo_users ||--o{ fixflo_fixture_sets : "foreign key"
  fixflo_users ||--o{ fixflo_fixtures : "foreign key"
  fixflo_users ||--o{ fixflo_generated_reports : "foreign key"
  fixflo_users ||--o{ fixflo_group_members : "foreign key"
  fixflo_users ||--o{ fixflo_groups : "foreign key"
  fixflo_users ||--o{ fixflo_notes : "foreign key"
  fixflo_users ||--o{ fixflo_report_templates : "foreign key"
  fixflo_users ||--o{ fixflo_report_types : "foreign key"
  fixflo_users ||--o{ fixflo_reports : "foreign key"
  fixflo_users ||--o{ fixflo_saved_filters : "foreign key"
  fixflo_users ||--o{ fixflo_saved_reports : "foreign key"
  fixflo_users ||--o{ fixflo_sessions : "foreign key"
  fixflo_users ||--o{ fixflo_sidebar_folders : "foreign key"
  fixflo_users ||--o{ fixflo_user_confidentiality_settings : "foreign key"
  fixflo_users ||--o{ fixflo_vessels : "foreign key"
  fixflo_users ||--o{ fixflo_widgets : "foreign key"
  fixflo_vessels ||--o{ fixflo_fixtures : "foreign key"
  fixflo_zones ||--o{ fixflo_boundaries : "foreign key"
  fixflo_zones ||--o{ fixflo_fixtures : "foreign key"
  fleetbase_api_credentials ||--o{ fleetbase_api_request_logs : "foreign key"
  fleetbase_api_credentials ||--o{ fleetbase_webhook_endpoints : "foreign key"
  fleetbase_api_credentials ||--o{ fleetbase_webhook_request_logs : "foreign key"
  fleetbase_api_events ||--o{ fleetbase_webhook_request_logs : "foreign key"
  fleetbase_billing_payment_gateways ||--o{ fleetbase_billing_plans : "foreign key"
  fleetbase_billing_payment_gateways ||--o{ fleetbase_billing_subscriptions : "foreign key"
  fleetbase_billing_plans ||--o{ fleetbase_billing_subscriptions : "foreign key"
  fleetbase_billing_subscriptions ||--o{ fleetbase_billing_subscription_items : "foreign key"
  fleetbase_categories ||--o{ fleetbase_entities : "foreign key"
  fleetbase_categories ||--o{ fleetbase_extensions : "foreign key"
  fleetbase_categories ||--o{ fleetbase_order_configs : "foreign key"
  fleetbase_categories ||--o{ fleetbase_storefront_network_stores : "foreign key"
  fleetbase_categories ||--o{ fleetbase_storefront_product_addon_categories : "foreign key"
  fleetbase_categories ||--o{ fleetbase_storefront_product_addons : "foreign key"
  fleetbase_categories ||--o{ fleetbase_storefront_products : "foreign key"
  fleetbase_chat_channels ||--o{ fleetbase_chat_attachments : "foreign key"
  fleetbase_chat_channels ||--o{ fleetbase_chat_logs : "foreign key"
  fleetbase_chat_channels ||--o{ fleetbase_chat_messages : "foreign key"
  fleetbase_chat_channels ||--o{ fleetbase_chat_participants : "foreign key"
  fleetbase_chat_messages ||--o{ fleetbase_chat_attachments : "foreign key"
  fleetbase_chat_messages ||--o{ fleetbase_chat_receipts : "foreign key"
  fleetbase_chat_participants ||--o{ fleetbase_chat_attachments : "foreign key"
  fleetbase_chat_participants ||--o{ fleetbase_chat_logs : "foreign key"
  fleetbase_chat_participants ||--o{ fleetbase_chat_messages : "foreign key"
  fleetbase_chat_participants ||--o{ fleetbase_chat_receipts : "foreign key"
  fleetbase_comments ||--o{ fleetbase_comments : "foreign key"
  fleetbase_companies ||--o{ fleetbase_api_credentials : "foreign key"
  fleetbase_companies ||--o{ fleetbase_api_request_logs : "foreign key"
  fleetbase_companies ||--o{ fleetbase_billing_customers : "foreign key"
  fleetbase_companies ||--o{ fleetbase_billing_subscriptions : "foreign key"
  fleetbase_companies ||--o{ fleetbase_chat_attachments : "foreign key"
  fleetbase_companies ||--o{ fleetbase_chat_channels : "foreign key"
  fleetbase_companies ||--o{ fleetbase_chat_logs : "foreign key"
  fleetbase_companies ||--o{ fleetbase_chat_messages : "foreign key"
  fleetbase_companies ||--o{ fleetbase_chat_participants : "foreign key"
  fleetbase_companies ||--o{ fleetbase_chat_receipts : "foreign key"
  fleetbase_companies ||--o{ fleetbase_comments : "foreign key"
  fleetbase_companies ||--o{ fleetbase_company_users : "foreign key"
  fleetbase_companies ||--o{ fleetbase_contacts : "foreign key"
  fleetbase_companies ||--o{ fleetbase_custom_field_values : "foreign key"
  fleetbase_companies ||--o{ fleetbase_custom_fields : "foreign key"
  fleetbase_companies ||--o{ fleetbase_drivers : "foreign key"
  fleetbase_companies ||--o{ fleetbase_entities : "foreign key"
  fleetbase_companies ||--o{ fleetbase_extension_installs : "foreign key"
  fleetbase_companies ||--o{ fleetbase_extensions : "foreign key"
  fleetbase_companies ||--o{ fleetbase_fleets : "foreign key"
  fleetbase_companies ||--o{ fleetbase_fuel_reports : "foreign key"
  fleetbase_companies ||--o{ fleetbase_groups : "foreign key"
  fleetbase_companies ||--o{ fleetbase_integrated_vendors : "foreign key"
  fleetbase_companies ||--o{ fleetbase_invites : "foreign key"
  fleetbase_companies ||--o{ fleetbase_issues : "foreign key"
  fleetbase_companies ||--o{ fleetbase_order_configs : "foreign key"
  fleetbase_companies ||--o{ fleetbase_orders : "foreign key"
  fleetbase_companies ||--o{ fleetbase_payloads : "foreign key"
  fleetbase_companies ||--o{ fleetbase_places : "foreign key"
  fleetbase_companies ||--o{ fleetbase_policies : "foreign key"
  fleetbase_companies ||--o{ fleetbase_positions : "foreign key"
  fleetbase_companies ||--o{ fleetbase_proofs : "foreign key"
  fleetbase_companies ||--o{ fleetbase_purchase_rates : "foreign key"
  fleetbase_companies ||--o{ fleetbase_roles : "foreign key"
  fleetbase_companies ||--o{ fleetbase_routes : "foreign key"
  fleetbase_companies ||--o{ fleetbase_service_areas : "foreign key"
  fleetbase_companies ||--o{ fleetbase_service_quotes : "foreign key"
  fleetbase_companies ||--o{ fleetbase_service_rates : "foreign key"
  fleetbase_companies ||--o{ fleetbase_tracking_numbers : "foreign key"
  fleetbase_companies ||--o{ fleetbase_tracking_statuses : "foreign key"
  fleetbase_companies ||--o{ fleetbase_transactions : "foreign key"
  fleetbase_companies ||--o{ fleetbase_types : "foreign key"
  fleetbase_companies ||--o{ fleetbase_users : "foreign key"
  fleetbase_companies ||--o{ fleetbase_vehicles : "foreign key"
  fleetbase_companies ||--o{ fleetbase_vendors : "foreign key"
  fleetbase_companies ||--o{ fleetbase_waypoints : "foreign key"
  fleetbase_companies ||--o{ fleetbase_webhook_endpoints : "foreign key"
  fleetbase_companies ||--o{ fleetbase_webhook_request_logs : "foreign key"
  fleetbase_companies ||--o{ fleetbase_zones : "foreign key"
  fleetbase_companies ||--o{ fleetbase_storefront_carts : "foreign key"
  fleetbase_companies ||--o{ fleetbase_storefront_checkouts : "foreign key"
  fleetbase_companies ||--o{ fleetbase_storefront_gateways : "foreign key"
  fleetbase_companies ||--o{ fleetbase_storefront_networks : "foreign key"
  fleetbase_companies ||--o{ fleetbase_storefront_notification_channels : "foreign key"
  fleetbase_companies ||--o{ fleetbase_storefront_payment_methods : "foreign key"
  fleetbase_companies ||--o{ fleetbase_storefront_products : "foreign key"
  fleetbase_companies ||--o{ fleetbase_storefront_stores : "foreign key"
  fleetbase_contacts ||--o{ fleetbase_storefront_reviews : "foreign key"
  fleetbase_contacts ||--o{ fleetbase_storefront_votes : "foreign key"
  fleetbase_custom_fields ||--o{ fleetbase_custom_field_values : "foreign key"
  fleetbase_dashboards ||--o{ fleetbase_dashboard_widgets : "foreign key"
  fleetbase_drivers ||--o{ fleetbase_entities : "foreign key"
  fleetbase_drivers ||--o{ fleetbase_fleet_drivers : "foreign key"
  fleetbase_drivers ||--o{ fleetbase_fuel_reports : "foreign key"
  fleetbase_drivers ||--o{ fleetbase_issues : "foreign key"
  fleetbase_drivers ||--o{ fleetbase_orders : "foreign key"
  fleetbase_extensions ||--o{ fleetbase_extension_installs : "foreign key"
  fleetbase_files ||--o{ fleetbase_billing_payment_gateways : "foreign key"
  fleetbase_files ||--o{ fleetbase_categories : "foreign key"
  fleetbase_files ||--o{ fleetbase_chat_attachments : "foreign key"
  fleetbase_files ||--o{ fleetbase_companies : "foreign key"
  fleetbase_files ||--o{ fleetbase_contacts : "foreign key"
  fleetbase_files ||--o{ fleetbase_extensions : "foreign key"
  fleetbase_files ||--o{ fleetbase_order_configs : "foreign key"
  fleetbase_files ||--o{ fleetbase_proofs : "foreign key"
  fleetbase_files ||--o{ fleetbase_users : "foreign key"
  fleetbase_files ||--o{ fleetbase_vehicles : "foreign key"
  fleetbase_files ||--o{ fleetbase_vendors : "foreign key"
  fleetbase_files ||--o{ fleetbase_storefront_gateways : "foreign key"
  fleetbase_files ||--o{ fleetbase_storefront_networks : "foreign key"
  fleetbase_files ||--o{ fleetbase_storefront_notification_channels : "foreign key"
  fleetbase_files ||--o{ fleetbase_storefront_products : "foreign key"
  fleetbase_files ||--o{ fleetbase_storefront_stores : "foreign key"
  fleetbase_fleets ||--o{ fleetbase_fleet_drivers : "foreign key"
  fleetbase_fleets ||--o{ fleetbase_fleet_vehicles : "foreign key"
  fleetbase_fleets ||--o{ fleetbase_fleets : "foreign key"
  fleetbase_groups ||--o{ fleetbase_group_users : "foreign key"
  fleetbase_integrated_vendors ||--o{ fleetbase_service_quotes : "foreign key"
  fleetbase_monitored_scheduled_tasks ||--o{ fleetbase_monitored_scheduled_task_log_items : "foreign key"
  fleetbase_order_configs ||--o{ fleetbase_orders : "foreign key"
  fleetbase_order_configs ||--o{ fleetbase_service_rates : "foreign key"
  fleetbase_orders ||--o{ fleetbase_drivers : "foreign key"
  fleetbase_orders ||--o{ fleetbase_positions : "foreign key"
  fleetbase_orders ||--o{ fleetbase_routes : "foreign key"
  fleetbase_orders ||--o{ fleetbase_storefront_checkouts : "foreign key"
  fleetbase_payloads ||--o{ fleetbase_entities : "foreign key"
  fleetbase_payloads ||--o{ fleetbase_orders : "foreign key"
  fleetbase_payloads ||--o{ fleetbase_purchase_rates : "foreign key"
  fleetbase_payloads ||--o{ fleetbase_service_quotes : "foreign key"
  fleetbase_payloads ||--o{ fleetbase_waypoints : "foreign key"
  fleetbase_permissions ||--o{ fleetbase_model_has_permissions : "foreign key"
  fleetbase_permissions ||--o{ fleetbase_role_has_permissions : "foreign key"
  fleetbase_places ||--o{ fleetbase_companies : "foreign key"
  fleetbase_places ||--o{ fleetbase_entities : "foreign key"
  fleetbase_places ||--o{ fleetbase_payloads : "foreign key"
  fleetbase_places ||--o{ fleetbase_positions : "foreign key"
  fleetbase_places ||--o{ fleetbase_vendors : "foreign key"
  fleetbase_places ||--o{ fleetbase_waypoints : "foreign key"
  fleetbase_places ||--o{ fleetbase_storefront_store_locations : "foreign key"
  fleetbase_policies ||--o{ fleetbase_model_has_policies : "foreign key"
  fleetbase_purchase_rates ||--o{ fleetbase_orders : "foreign key"
  fleetbase_roles ||--o{ fleetbase_model_has_roles : "foreign key"
  fleetbase_roles ||--o{ fleetbase_role_has_permissions : "foreign key"
  fleetbase_routes ||--o{ fleetbase_orders : "foreign key"
  fleetbase_service_areas ||--o{ fleetbase_fleets : "foreign key"
  fleetbase_service_areas ||--o{ fleetbase_service_areas : "foreign key"
  fleetbase_service_areas ||--o{ fleetbase_service_rates : "foreign key"
  fleetbase_service_areas ||--o{ fleetbase_zones : "foreign key"
  fleetbase_service_quotes ||--o{ fleetbase_purchase_rates : "foreign key"
  fleetbase_service_quotes ||--o{ fleetbase_service_quote_items : "foreign key"
  fleetbase_service_quotes ||--o{ fleetbase_storefront_checkouts : "foreign key"
  fleetbase_service_rates ||--o{ fleetbase_service_quotes : "foreign key"
  fleetbase_service_rates ||--o{ fleetbase_service_rate_fees : "foreign key"
  fleetbase_service_rates ||--o{ fleetbase_service_rate_parcel_fees : "foreign key"
  fleetbase_tracking_numbers ||--o{ fleetbase_entities : "foreign key"
  fleetbase_tracking_numbers ||--o{ fleetbase_orders : "foreign key"
  fleetbase_tracking_numbers ||--o{ fleetbase_tracking_statuses : "foreign key"
  fleetbase_tracking_numbers ||--o{ fleetbase_waypoints : "foreign key"
  fleetbase_tracking_statuses ||--o{ fleetbase_tracking_numbers : "foreign key"
  fleetbase_transactions ||--o{ fleetbase_orders : "foreign key"
  fleetbase_transactions ||--o{ fleetbase_purchase_rates : "foreign key"
  fleetbase_transactions ||--o{ fleetbase_transaction_items : "foreign key"
  fleetbase_types ||--o{ fleetbase_extensions : "foreign key"
  fleetbase_types ||--o{ fleetbase_vendors : "foreign key"
  fleetbase_users ||--o{ fleetbase_api_credentials : "foreign key"
  fleetbase_users ||--o{ fleetbase_chat_channels : "foreign key"
  fleetbase_users ||--o{ fleetbase_chat_participants : "foreign key"
  fleetbase_users ||--o{ fleetbase_comments : "foreign key"
  fleetbase_users ||--o{ fleetbase_companies : "foreign key"
  fleetbase_users ||--o{ fleetbase_company_users : "foreign key"
  fleetbase_users ||--o{ fleetbase_drivers : "foreign key"
  fleetbase_users ||--o{ fleetbase_fuel_reports : "foreign key"
  fleetbase_users ||--o{ fleetbase_group_users : "foreign key"
  fleetbase_users ||--o{ fleetbase_integrated_vendors : "foreign key"
  fleetbase_users ||--o{ fleetbase_invites : "foreign key"
  fleetbase_users ||--o{ fleetbase_issues : "foreign key"
  fleetbase_users ||--o{ fleetbase_order_configs : "foreign key"
  fleetbase_users ||--o{ fleetbase_orders : "foreign key"
  fleetbase_users ||--o{ fleetbase_user_devices : "foreign key"
  fleetbase_users ||--o{ fleetbase_webhook_endpoints : "foreign key"
  fleetbase_users ||--o{ fleetbase_storefront_carts : "foreign key"
  fleetbase_users ||--o{ fleetbase_storefront_gateways : "foreign key"
  fleetbase_users ||--o{ fleetbase_storefront_networks : "foreign key"
  fleetbase_users ||--o{ fleetbase_storefront_notification_channels : "foreign key"
  fleetbase_users ||--o{ fleetbase_storefront_product_addons : "foreign key"
  fleetbase_users ||--o{ fleetbase_storefront_products : "foreign key"
  fleetbase_users ||--o{ fleetbase_storefront_reviews : "foreign key"
  fleetbase_users ||--o{ fleetbase_storefront_store_locations : "foreign key"
  fleetbase_users ||--o{ fleetbase_storefront_stores : "foreign key"
  fleetbase_users ||--o{ fleetbase_storefront_votes : "foreign key"
  fleetbase_vehicle_devices ||--o{ fleetbase_vehicle_device_events : "foreign key"
  fleetbase_vehicles ||--o{ fleetbase_drivers : "foreign key"
  fleetbase_vehicles ||--o{ fleetbase_fleet_vehicles : "foreign key"
  fleetbase_vehicles ||--o{ fleetbase_fuel_reports : "foreign key"
  fleetbase_vehicles ||--o{ fleetbase_issues : "foreign key"
  fleetbase_vehicles ||--o{ fleetbase_vehicle_devices : "foreign key"
  fleetbase_vendors ||--o{ fleetbase_drivers : "foreign key"
  fleetbase_vendors ||--o{ fleetbase_entities : "foreign key"
  fleetbase_vendors ||--o{ fleetbase_fleets : "foreign key"
  fleetbase_vendors ||--o{ fleetbase_vehicles : "foreign key"
  fleetbase_webhook_endpoints ||--o{ fleetbase_webhook_request_logs : "foreign key"
  fleetbase_zones ||--o{ fleetbase_fleets : "foreign key"
  fleetbase_zones ||--o{ fleetbase_service_rates : "foreign key"
  fleetbase_storefront_carts ||--o{ fleetbase_storefront_checkouts : "foreign key"
  fleetbase_storefront_checkouts ||--o{ fleetbase_storefront_carts : "foreign key"
  fleetbase_storefront_gateways ||--o{ fleetbase_storefront_checkouts : "foreign key"
  fleetbase_storefront_gateways ||--o{ fleetbase_storefront_payment_methods : "foreign key"
  fleetbase_storefront_networks ||--o{ fleetbase_storefront_checkouts : "foreign key"
  fleetbase_storefront_networks ||--o{ fleetbase_storefront_network_stores : "foreign key"
  fleetbase_storefront_product_variants ||--o{ fleetbase_storefront_product_variant_options : "foreign key"
  fleetbase_storefront_products ||--o{ fleetbase_storefront_product_addon_categories : "foreign key"
  fleetbase_storefront_products ||--o{ fleetbase_storefront_product_hours : "foreign key"
  fleetbase_storefront_products ||--o{ fleetbase_storefront_product_store_locations : "foreign key"
  fleetbase_storefront_products ||--o{ fleetbase_storefront_product_variants : "foreign key"
  fleetbase_storefront_store_locations ||--o{ fleetbase_storefront_product_store_locations : "foreign key"
  fleetbase_storefront_store_locations ||--o{ fleetbase_storefront_store_hours : "foreign key"
  fleetbase_storefront_stores ||--o{ fleetbase_storefront_checkouts : "foreign key"
  fleetbase_storefront_stores ||--o{ fleetbase_storefront_network_stores : "foreign key"
  fleetbase_storefront_stores ||--o{ fleetbase_storefront_payment_methods : "foreign key"
  fleetbase_storefront_stores ||--o{ fleetbase_storefront_products : "foreign key"
  fleetbase_storefront_stores ||--o{ fleetbase_storefront_store_locations : "foreign key"
