<?php

/*
 * CI helper: mint a working Fleetbase public-API key against a booted stack.
 *
 * Run it by piping into the application container's tinker:
 *   docker compose exec -T application php artisan tinker < scripts/ci/mint-api-key.php
 *
 * It creates (idempotently) an organization + owner user + a live API credential and
 * prints the `flb_live_...` key on its own line. The public API middleware
 * (AuthenticateOnceWithBasicAuth) authenticates `Authorization: Bearer <key>` against
 * the api_credentials.key column, and requires the company to have an owner.
 *
 * The key value is generated by ApiCredentialObserver on insert, so the credential
 * MUST be created through the Eloquent model (not a raw insert), then reloaded.
 */

use Fleetbase\Models\ApiCredential;
use Fleetbase\Models\Company;
use Fleetbase\Models\User;

$company = Company::firstOrCreate(['name' => 'CI Contract Org']);

$user = User::firstOrCreate(
    ['email' => 'ci-contract@fleetbase.local'],
    ['name' => 'CI Contract User', 'company_uuid' => $company->uuid, 'status' => 'active']
);
$user->type     = 'user';
$user->password = 'CiContract1!' . bin2hex(random_bytes(6));
$user->save();

// The company must have an owner or the API-key middleware rejects requests (401).
$company->setOwner($user, true);
$company->save();

// test_mode=false => flb_live_ key stored on the default (mysql) connection.
$credential = ApiCredential::firstOrCreate(
    ['company_uuid' => $company->uuid, 'name' => 'CI Contract Key'],
    ['user_uuid' => $user->uuid, 'test_mode' => false]
);

echo PHP_EOL . $credential->fresh()->key . PHP_EOL;
