// scripts/ci/mint-api-key.php
//
// CI helper: mint a working Fleetbase public-API key against a booted stack.
//
// This file is NOT a standalone script. It is base64-encoded and eval()'d inside
// `php artisan tinker --execute="eval(base64_decode('...'));"`. Piping a file that
// begins with a <?php tag to tinker triggers a PsySH parse error ("unexpected '<'"),
// so this snippet intentionally OMITS the opening <?php tag and uses fully-qualified
// class names instead of `use` statements.
//
// It idempotently creates an organization + owner user + a live API credential and
// prints the flb_live_ key. The key is generated by ApiCredentialObserver on insert,
// so the credential MUST be created through the Eloquent model, then reloaded. The
// company must have an owner or the public-API middleware rejects the key (401).

try {
    $company = \Fleetbase\Models\Company::firstOrCreate(['name' => 'CI Contract Org']);

    $user = \Fleetbase\Models\User::where('email', 'ci-contract@fleetbase.local')->first();
    if (!$user) {
        $user               = new \Fleetbase\Models\User();
        $user->name         = 'CI Contract User';
        $user->email        = 'ci-contract@fleetbase.local';
        $user->company_uuid = $company->uuid;
        $user->type         = 'user';
        $user->status       = 'active';
        $user->password     = 'CiContract1!' . bin2hex(random_bytes(6));
        $user->save();
    }

    if (empty($company->owner_uuid)) {
        $company->setOwner($user, true);
        $company->save();
    }

    // test_mode=false => flb_live_ key stored on the default (mysql) connection.
    $credential = \Fleetbase\Models\ApiCredential::firstOrCreate(
        ['company_uuid' => $company->uuid, 'name' => 'CI Contract Key'],
        ['user_uuid' => $user->uuid, 'test_mode' => false]
    );

    echo PHP_EOL . 'MINTED_API_KEY=' . $credential->fresh()->key . PHP_EOL;

    // A handful of endpoints (organizations listing, driver onboarding) sit behind
    // AuthenticatePlatformApiToken rather than an org API credential, and answer 401
    // to an flb_live_ key. Only the hash is persisted, so the plaintext cannot be read
    // back — rotating is the only way to learn a usable token. Safe here because this
    // script only ever runs against a throwaway CI stack; do not run it against an
    // install whose platform token is already in use.
    $platformToken = \Fleetbase\Support\PlatformApi::rotateToken();
    echo 'MINTED_PLATFORM_TOKEN=' . $platformToken . PHP_EOL;
} catch (\Throwable $e) {
    echo PHP_EOL . 'MINT_ERROR: ' . get_class($e) . ': ' . $e->getMessage() . PHP_EOL;
    echo $e->getFile() . ':' . $e->getLine() . PHP_EOL;
}
