#!/bin/sh

set -eu

CONFIG_FILE="/usr/share/nginx/html/fleetbase.config.json"

API_HOST="${API_HOST:-http://localhost:8000}"
API_NAMESPACE="${API_NAMESPACE:-int/v1}"
SOCKETCLUSTER_PATH="${SOCKETCLUSTER_PATH:-/socketcluster/}"
SOCKETCLUSTER_HOST="${SOCKETCLUSTER_HOST:-}"
SOCKETCLUSTER_SECURE="${SOCKETCLUSTER_SECURE:-false}"
SOCKETCLUSTER_PORT="${SOCKETCLUSTER_PORT:-38000}"
OSRM_HOST="${OSRM_HOST:-https://router.project-osrm.org}"
EXTENSIONS="${EXTENSIONS:-}"

cat > "$CONFIG_FILE" <<JSON
{
    "API_HOST": "$API_HOST",
    "API_NAMESPACE": "$API_NAMESPACE",
    "SOCKETCLUSTER_PATH": "$SOCKETCLUSTER_PATH",
    "SOCKETCLUSTER_HOST": "$SOCKETCLUSTER_HOST",
    "SOCKETCLUSTER_SECURE": "$SOCKETCLUSTER_SECURE",
    "SOCKETCLUSTER_PORT": "$SOCKETCLUSTER_PORT",
    "OSRM_HOST": "$OSRM_HOST",
    "EXTENSIONS": "$EXTENSIONS"
}
JSON

exec "$@"