linkWorkspacePackages: deep
preferWorkspacePackages: true
publicHoistPattern:
  - "*ember-core*"
  - "*ember-ui*"
  - "*fleetops-data*"
overrides:
  "@fleetbase/fleetops-data": "^0.2.2"
  "@fleetbase/ember-core": "^0.3.24"
  "@fleetbase/ember-ui": "^0.4.3"
allowBuilds:
  "@fortawesome/fontawesome-common-types": false
  "@fortawesome/fontawesome-svg-core": false
  "@fortawesome/free-brands-svg-icons": false
  "@fortawesome/free-solid-svg-icons": false
  core-js: false
  fsevents: false
minimumReleaseAgeExclude:
  - '@fleetbase/ai-engine@0.0.5'
  - '@fleetbase/customer-portal-engine@0.0.14'
  - '@fleetbase/dev-engine@0.2.16'
  - '@fleetbase/ember-ui@0.4.3'
  - '@fleetbase/fleetops-data@0.2.2'
  - '@fleetbase/fleetops-engine@0.6.69'
  - '@fleetbase/iam-engine@0.1.12'
