allowBuilds:
  '@fortawesome/fontawesome-common-types': false
  '@fortawesome/fontawesome-svg-core': false
  '@fortawesome/free-brands-svg-icons': false
  '@fortawesome/free-solid-svg-icons': false
  core-js: false
  fsevents: false
