name: Backend Deployment Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'
        required: true
        type: choice
        options:
          - dev
          - test
          - live

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Deploy to Dev/Live environment(SSH Key)
        if: ${{ inputs.environment == 'dev' || inputs.environment == 'live' }}
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd ${{ inputs.environment == 'dev' && '/home/ubuntu/fleetbase_agilecyber/fleetbase' || '/var/www/html/afp.fleetyes.com/htdocs/' }}
            git pull
            cd ${{ inputs.environment == 'dev' && '/home/ubuntu/fleetbase_agilecyber/fleetbase/api' || '/var/www/html/afp.fleetyes.com/htdocs/api/' }}
            php artisan migrate
            php artisan cache:clear

      - name: Deploy to Test environment (SSH Password)
        if: ${{ inputs.environment == 'test' }}
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd /var/www/html/fleetyes.com/domains/dashboard/
            git pull
            cd /var/www/html/fleetyes.com/domains/dashboard/api/
            php artisan migrate
            php artisan cache:clear